[package]
name = "tetsuki-actix"
version = "0.1.0"
authors = ["Chehui Chou <deadshot465@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-service = "~2.0.0-beta.4"
actix-web = "~4.0.0-beta.3"
anyhow = "~1.0.38"
chrono = "~0.4.19"
dotenv = "~0.15.0"
env_logger = "~0.8.3"
funty = "=1.1.0"
futures = "~0.3.12"
jsonwebtoken = "~7.2.0"
log = "~0.4.14"
once_cell = "~1.5.2"
serde = "~1.0.123"
serde_json = "~1.0.62"
sqlx = { version = "~0.5.1", features = ["postgres", "runtime-actix-rustls", "json"] }